### PR TITLE
Fix vagrant master create --name

### PR DESCRIPTION
**Pull request by j-a-m-l**
This PR fixes some problems of the `--name` option of the `kontena vagrant master create` command.

### CODE REVIEW

**Comment by j-a-m-l** [comment]
PR is failed while installing gems. Maybe it was a temporary issue?

**Comment by jnummelin** [comment]
There seems to be too old ruby version in the build matrix to work properly with the "main" cli. Does not have anything to do with this PR, I'll whip up another to fix that.

**Comment by jnummelin** [comment]
Maybe while you at it, fix the provisioner to actually use the name:
https://github.com/kontena/kontena-plugin-vagrant/blob/master/lib/kontena/machine/vagrant/master_provisioner.rb#L23

**Comment by j-a-m-l** [comment]
Done.

**Comment by jnummelin** [comment]
Tested locally and works now as expected.

I think we should wait with this until #38 gets merged so this could be rebased. Travis can really test it also then.

**Pull request merged**
